version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: my-postgres-db
    env_file:
      - /Users/jonatanav255/Documents/GitHub/tic-tac-toe/scripts/.env.postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
